"""Generates quiz questions straight from verified data, so no answer is written from memory.

Sources (downloaded from GitHub):
  - Quran text and index: fawazahmed0/quran-api (ara-quransimple + info.json: surah order, verse counts,
    Meccan/Medinan, juz, sajdas)
  - The Forty Hadith of an-Nawawi: fawazahmed0/hadith-api (ara-nawawi)
  - Asma ul-Husna and their meanings: app/src/main/java/com/mohamed/safi/faith/AsmaHusna.kt (already in the app)

Writes religion_v_quran.py, religion_v_hadith.py, religion_v_asma.py and general_v_math.py next to this file
(the Q lists build.py reads). Run:  python3 tools/quiz/gen_verified.py && python3 tools/quiz/build.py
Deterministic: the same data gives the same questions.
"""
import json, os, random, re, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
RAW = "https://raw.githubusercontent.com/fawazahmed0/"
AR_DIGITS = str.maketrans("0123456789", "٠١٢٣٤٥٦٧٨٩")


def get(url):
    return json.loads(urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"}), timeout=120).read())


def ar(n):
    return str(n).translate(AR_DIGITS)


DIAC = re.compile(r"[ؐ-ًؚ-ٰٟۖ-ۭ]")


def plain(s):
    return DIAC.sub("", s)


def write(name, qs):
    seen, out = set(), []
    for q in qs:
        if (q[0], q[1]) in seen or len(set(q[1:5])) != 4:
            continue
        seen.add((q[0], q[1])); out.append(q)
    with open(os.path.join(HERE, name), "w", encoding="utf-8") as f:
        f.write("# Generated by gen_verified.py from verified data. Do not edit by hand.\nQ = [\n")
        for q in out:
            f.write("    " + repr(tuple(q)) + ",\n")
        f.write("]\n")
    print(name, len(out))


def near_numbers(n, r, k=3, lo=1):
    opts = set()
    spread = max(3, n // 6)
    while len(opts) < k:
        d = r.randint(1, spread) * r.choice((-1, 1))
        if n + d >= lo and n + d != n:
            opts.add(n + d)
    return [ar(x) for x in opts]


STD_NAMES = ("الفاتحة،البقرة،آل عمران،النساء،المائدة،الأنعام،الأعراف،الأنفال،التوبة،يونس،هود،يوسف،الرعد،إبراهيم،الحجر،النحل،"
             "الإسراء،الكهف،مريم،طه،الأنبياء،الحج،المؤمنون،النور،الفرقان،الشعراء،النمل،القصص،العنكبوت،الروم،لقمان،السجدة،"
             "الأحزاب،سبأ،فاطر،يس،الصافات،ص،الزمر،غافر،فصلت،الشورى،الزخرف،الدخان،الجاثية،الأحقاف،محمد،الفتح،الحجرات،ق،"
             "الذاريات،الطور،النجم،القمر،الرحمن،الواقعة،الحديد،المجادلة،الحشر،الممتحنة،الصف،الجمعة،المنافقون،التغابن،الطلاق،"
             "التحريم،الملك،القلم،الحاقة،المعارج،نوح،الجن،المزمل،المدثر،القيامة،الإنسان،المرسلات،النبأ،النازعات،عبس،التكوير،"
             "الانفطار،المطففين،الانشقاق،البروج،الطارق،الأعلى،الغاشية،الفجر،البلد،الشمس،الليل،الضحى،الشرح،التين،العلق،القدر،"
             "البينة،الزلزلة،العاديات،القارعة،التكاثر،العصر،الهمزة،الفيل،قريش،الماعون،الكوثر،الكافرون،النصر،المسد،الإخلاص،"
             "الفلق،الناس")


def quran():
    info = get(RAW + "quran-api/1/info.json")
    text = get(RAW + "quran-api/1/editions/ara-quransimple.json")["quran"]
    ch = info["chapters"]
    # the standard spelling of the surah names (the source's own spelling drops hamzas and alifs)
    name = dict(enumerate(STD_NAMES.split("،"), 1))
    assert len(name) == 114
    verses = {}
    for v in text:
        verses.setdefault(v["chapter"], []).append(v["text"])
    r = random.Random(114)
    Q = []
    famous = {1, 2, 18, 36, 55, 56, 67, 103, 108, 112, 113, 114}
    for c in ch:
        n, nv = c["chapter"], len(c["verses"])
        sname = name[n]
        lvl = 2 if n in famous or nv <= 6 else 3
        w = near_numbers(nv, r)
        Q.append((f"كم عدد آيات سورة {sname}؟", ar(nv), *w, "quran", lvl, f"سورة {sname} {ar(nv)} آية."))
        # order in the mushaf
        others = r.sample([x for x in name if abs(x - n) <= 6 and x != n] or [x for x in name if x != n], 3)
        Q.append((f"ما ترتيب سورة {sname} في المصحف؟", ar(n), *[ar(o) for o in others], "quran", 2 if n in famous else 3, f"سورة {sname} هي السورة رقم {ar(n)}."))
        if n < 114:
            nxt = name[n + 1]
            wrong = r.sample([name[x] for x in name if x not in (n, n + 1)], 3)
            Q.append((f"ما السورة التي تأتي بعد سورة {sname} في ترتيب المصحف؟", nxt, *wrong, "quran", 2 if n >= 78 else 3, f"بعد سورة {sname} تأتي سورة {nxt}."))
        juz = c["verses"][0]["juz"]
        jw = near_numbers(juz, r, lo=1)
        jw = [x for x in jw]
        if all(1 <= int(x.translate(str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789"))) <= 30 for x in jw):
            Q.append((f"في أي جزء تبدأ سورة {sname}؟", ar(juz), *jw, "quran", 3, f"تبدأ سورة {sname} في الجزء {ar(juz)}."))
    # Medinan among Meccan (and the reverse)
    # surahs whose Meccan/Medinan status scholars differ on are left out of these questions
    disputed = {13, 22, 47, 55, 57, 61, 64, 76, 83, 97, 98, 99, 110, 112, 113, 114}
    med = [c["chapter"] for c in ch if c["revelation"].lower().startswith(("med", "mad")) and c["chapter"] not in disputed]
    mec = [c["chapter"] for c in ch if not c["revelation"].lower().startswith(("med", "mad")) and c["chapter"] not in disputed]
    for m in med:
        w = r.sample(mec, 3)
        Q.append(("أي هذه السور مدنية؟", name[m], *[name[x] for x in w], "quran", 2,
                  f"سورة {name[m]} مدنية، والسور الأخرى في الاختيارات مكية."))
    for m in r.sample(mec, 30):
        w = r.sample(med, 3)
        Q.append(("أي هذه السور مكية؟", name[m], *[name[x] for x in w], "quran", 2,
                  f"سورة {name[m]} مكية، والسور الأخرى في الاختيارات مدنية."))
    # sajdas
    sajda_surahs = sorted({s["chapter"] for s in info["sajdas"]["references"]}) if isinstance(info.get("sajdas"), dict) else []
    non_sajda = [x for x in name if x not in sajda_surahs]
    for s in sajda_surahs:
        Q.append(("أي هذه السور فيها سجدة تلاوة؟", name[s], *[name[x] for x in r.sample(non_sajda, 3)], "quran", 3,
                  f"في سورة {name[s]} موضع سجدة تلاوة."))
    # which surah is this ayah from / complete the ayah
    pool = [(n, i, t) for n, vs in verses.items() for i, t in enumerate(vs, 1) if 40 <= len(t) <= 130 and not t.startswith("بسم الله")]
    r.shuffle(pool)
    used = set()
    k1 = 0
    for n, i, t in pool:
        if k1 >= 350: break
        key = plain(t)
        if key in used: continue
        # skip verses that repeat word for word elsewhere
        if sum(1 for vs in verses.values() for x in vs if x == t) > 1: continue
        used.add(key)
        wrong = r.sample([x for x in name if x != n], 3)
        Q.append((f"في أي سورة وردت هذه الآية: ﴿{t}﴾؟", name[n], *[name[x] for x in wrong], "quran", 3, f"الآية {ar(i)} من سورة {name[n]}."))
        k1 += 1
    k2 = 0
    for n, i, t in pool:
        if k2 >= 350: break
        words = t.split()
        if len(words) < 8: continue
        cut = len(words) // 2
        start, end = " ".join(words[:cut]), " ".join(words[cut:])
        # wrong endings: second halves of other verses with a similar length
        cands = [v.split() for v in verses[n] if v != t and len(v.split()) >= 6] + [v.split() for v in r.choice(list(verses.values())) if v != t and len(v.split()) >= 6]
        ends = []
        for cw in cands:
            e = " ".join(cw[len(cw) // 2:])
            if e != end and e not in ends and abs(len(e) - len(end)) < 25:
                ends.append(e)
        if len(ends) < 3: continue
        r.shuffle(ends)
        Q.append((f"أكمل الآية: ﴿{start} …﴾", end, *ends[:3], "quran", 3, f"﴿{t}﴾ — سورة {name[n]}، الآية {ar(i)}."))
        k2 += 1
    write("religion_v_quran.py", Q)


def hadith():
    d = get(RAW + "hadith-api/1/editions/ara-nawawi.json")
    hs = [h["text"] for h in d["hadiths"]]
    r = random.Random(40)
    Q = []
    # the Prophet's words usually start after the first quote mark
    bodies = []
    for idx, t in enumerate(hs, 1):
        m = re.search(r"[\"«“](.+)", t)
        body = (m.group(1) if m else t).strip(' "»”')
        words = body.split()
        if len(words) < 10: continue
        bodies.append((idx, body, words))
    for idx, body, words in bodies:
        start = " ".join(words[:6])
        end = " ".join(words[6:14])
        others = [" ".join(w[6:14]) for j, b, w in bodies if j != idx]
        others = [o for o in others if o != end]
        if len(others) < 3: continue
        Q.append((f"أكمل الحديث (الأربعون النووية رقم {ar(idx)}): «{start} …»", end, *r.sample(others, 3), "hadith", 3,
                  f"الحديث رقم {ar(idx)} من الأربعين النووية."))
    write("religion_v_hadith.py", Q)


def asma():
    src = open(os.path.join(ROOT, "app/src/main/java/com/mohamed/safi/faith/AsmaHusna.kt"), encoding="utf-8").read()
    pairs = re.findall(r'"([^"]+)" to "([^"]+)"', src)
    r = random.Random(99)
    Q = []
    names = [p[0] for p in pairs]
    for n, mean in pairs:
        if n == "الله": continue
        wrong = r.sample([x for x in names if x != n], 3)
        Q.append((f"أي اسم من أسماء الله الحسنى معناه: {mean}؟", n, *wrong, "aqeedah", 2, f"{n}: {mean}."))
    write("religion_v_asma.py", Q)


def math():
    r = random.Random(7)
    Q = []
    for _ in range(60):
        a, b = r.randint(12, 99), r.randint(3, 19)
        c = a * b
        Q.append((f"كم حاصل {ar(a)} × {ar(b)}؟", ar(c), ar(c + b), ar(c - b), ar(c + 10), "math", 2, f"{ar(a)} × {ar(b)} = {ar(c)}."))
    for _ in range(40):
        a, b = r.randint(120, 999), r.randint(45, 499)
        c = a + b
        Q.append((f"كم مجموع {ar(a)} + {ar(b)}؟", ar(c), ar(c + 10), ar(c - 1), ar(c + 100), "math", 1, f"{ar(a)} + {ar(b)} = {ar(c)}."))
    for _ in range(40):
        st, d = r.randint(1, 20), r.randint(2, 9)
        seq = [st + d * i for i in range(5)]
        nx = st + d * 5
        Q.append((f"أكمل المتتالية: {'، '.join(ar(x) for x in seq)}، …؟", ar(nx), ar(nx + 1), ar(nx - d + 1), ar(nx + d), "math", 2, f"كل مرة بنزود {ar(d)}، فالتالي {ar(nx)}."))
    for _ in range(30):
        st, m = r.randint(1, 5), r.choice((2, 3))
        seq = [st * m ** i for i in range(5)]
        nx = st * m ** 5
        Q.append((f"أكمل المتتالية: {'، '.join(ar(x) for x in seq)}، …؟", ar(nx), ar(nx + st), ar(seq[-1] + seq[-2]), ar(nx * 2), "math", 3, f"كل رقم مضروب في {ar(m)}، فالتالي {ar(nx)}."))
    for _ in range(30):
        p, base = r.choice((10, 20, 25, 50, 75)), r.choice((40, 80, 120, 200, 360, 400, 600, 1000))
        v = base * p // 100
        Q.append((f"كم يساوي {ar(p)}٪ من {ar(base)}؟", ar(v), ar(v + 5), ar(v * 2), ar(max(1, v - 10)), "math", 2, f"{ar(base)} × {ar(p)} ÷ ١٠٠ = {ar(v)}."))
    write("general_v_math.py", Q)


if __name__ == "__main__":
    quran(); hadith(); asma(); math()
